#cloud-config
fqdn: localhost
hostname: localhost
create_hostname_file: true
prefer_fqdn_over_hostname: true
manage_etc_hosts: true

package_update: true
package_upgrade: false
packages:
  - qemu-guest-agent

runcmd:
  - systemctl enable --now qemu-guest-agent
  - sed -i 's/^#\?PermitRootLogin .*/PermitRootLogin yes/' /etc/ssh/sshd_config
  - systemctl restart sshd

users:
  - name: root
    shell: /bin/bash
    lock_passwd: false

disable_root: false
ssh_pwauth: true

chpasswd:
  expire: false

network:
  version: 2
  ethernets:
    eth0:
      dhcp4: true